use water;

CREATE TABLE IF NOT EXISTS water.scenario1
(
 `id` int NOT NULL AUTO_INCREMENT,
 `toc_no` varchar(50) NOT NULL,
 `cnsmr_no` varchar(100) NOT NULL,
 `mesure_de` varchar(50) NOT NULL,
 `mesure_tm` varchar(50) NOT NULL,
 `legal_dong_cd` varchar(50) NOT NULL,
 `sg_pwrer_use_am` FLOAT NOT NULL,
 `all_pwrer_usm_am` FLOAT NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='scenario 1';

CREATE TABLE IF NOT EXISTS water.scenario2
(
 `id` int NOT NULL AUTO_INCREMENT,
  rnum float,
  fclt_nam varchar(50),
  regn_cty varchar(50),
  brtc_nm varchar(50),
  signgu_nm varchar(50),
  telno varchar(50),
  coll_dat varchar(50),
  inorg_nam varchar(50),
  tcc float,
  tc varchar(50),
  efc varchar(50),
  pb float,
  fl float,
  as1 float,
  se float,
  hg float,
  cn float,
  cr float,
  nhn float,
  non float,
  cd float,
  bor float,
  bro float,
  durnm float NULL,
  phen float,
  dia float,
  para float,
  peni float,
  cbr float,
  tce float,
  ttce float,
  tcf float,
  cc float,
  dde float,
  dcm float,
  bz float,
  tol float,
  eb float,
  xyl float,
  dbcp float,
  diox float,
  rc float,
  thms float,
  cf float,
  bdcm float,
  dbcm float,
  ch float,
  dit float,
  trt float,
  trl float,
  has float,
  foah float,
  hr float,
  kmn float,
  odor varchar(50),
  tw varchar(50),
  cu float,
  cw float,
  dtg float,
  ph float,
  zn float,
  cl float,
  re float,
  fe float,
  mn float,
  tu float,
  so float,
  al float,
  update_dat datetime,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='scenario 2';


